### ISSUE TITLE
zipfile van informatiemodel automatisch aanbieden

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/technisch-register#12]
Van ieder informatiemodel wordt automatisch een zipfile gegenereerd en aangeboden op de overzichtspagina van dat informatiemodel.
Dit is met name handig wanneer je een zipfile op de reguliere website wil aanbieden. Bijvoorbeeld BGT-IMGeo op de geonovum website

**Comment by ndkv** [comment]
GitHub bakt van elke release automatisch een .zip. Deze kunnen we in HTML pagina's aanbieden als link of in mapje van elke informatiemodel als een .zip bestand. 

@nicojanbakker kun je dit oppakken?

**Comment by ghost** [comment]
Ja komt voor elkaar!

Op 8 december 2015 11:51 schreef Simeon Nedkov notifications@github.com:

**Comment by ndkv** [comment]
Geleverd door bd80d662e6b6f22f3f3eb1167271e290616758bf.
