### ISSUE TITLE
call('chmod ...') vervangen?

### ISSUE THREAD

**Issue by ndkv** [Geonovum/technisch-register#24]
`call('chmod...', shell=True)` is niet fancy maar het werkt wel. :relaxed: 

Ik heb met `chmod` module gespeeld https://github.com/Geonovum/technisch-register/commit/77c52ec11af0ba992c01f86fc5f911daeaf3da9c maar dat werkte niet (goed) op de server. 

We kunnen ook beslissen om het zo te laten aangezien het prima werkt.

**Comment by ghost** [comment]
Ja daar ben ik het mee eens. Het belangrijkste is dat het werkt. Mooi maken kan, indien gewenst, altijd nog.
