### ISSUE TITLE
IM in navigatiebalk is overal IMGeo

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/technisch-register#27]
ik kreeg onderstaande observatie van Wilko binnen:
Hi Frank,

Vanavond zit ik wat in het technisch register te surfen (erg leuk!), ik zie nog een klein foutje. Als je bijvoorbeeld kijkt op:
    http://register.geostandaarden.nl/imro/index.html
Dan staat in de groene navigatiebalk IMGeo en ik denk dat daar IMRO had moeten staan.

Overigens staat er bij alle informatiemodellen IMGeo.

Groet, Wilko

**Comment by ndkv** [comment]
Goed gespot! 

Waardes op lijn 19 in `standard.html` moeten automatisch aangepast worden, zie https://github.com/Geonovum/technisch-register/blob/master/web/templates/standard.html#L19

Dit kan het beste in `create_standard_webpage` functie in `webpages.py` gedaan worden.
