### ISSUE TITLE
Clusters en clustering

### ISSUE THREAD

**Issue by ndkv** [Geonovum/technisch-register#34]
@ghost Ik heb de clusters https://github.com/Geonovum/technisch-register/pull/33 aan de praat gekregen. Fraai!

Ik probeer uit te vogelen hoe het precies werkt. Klopt het dat je voor elke categorie in `clusters.json` een apart mapje op de server maakt en daar alle standaarden heen kopieert die onderdeel zijn van het cluster?

Als ik je script vanuit het `imkl` repo aanroep (door `name` op lijn 44 van `github-payload.json` de waarde `imkl` te geven) krijg ik in het `staging/register` mapje het volgende te zien

```
drwxr-xr-x@ 10 simeon  staff   340 Dec 16 14:15 .
drwxr-xr-x@  8 simeon  staff   272 Dec 16 14:15 ..
drwxr-xr-x@  3 simeon  staff   102 Dec 16 14:15 gmlapplicatieschema
-rwxr-xr-x@  1 simeon  staff  6999 Dec 16 14:15 index.html
drwxr-xr-x@  3 simeon  staff   102 Dec 16 14:15 informatiemodel
drwxr-xr-x@  4 simeon  staff   136 Dec 16 14:15 overig
drwxr-xr-x@  6 simeon  staff   204 Dec 16 14:15 r
drwxr-xr-x@  3 simeon  staff   102 Dec 16 14:15 symbool
drwxr-xr-x@  3 simeon  staff   102 Dec 16 14:15 visualisatie
drwxr-xr-x@  3 simeon  staff   102 Dec 16 14:15 waardelijst
```

Het mapje `imkl` zit in `overig`. 

Deze aanpak is problematisch omdat het de URLs in het technisch register (TR) verandert. `imkl` is nu beschikbaar op 

```
http://register.geostandaarden.nl/overig/imkl
```

in plaats van 

```
http://register.geostandaarden.nl/imkl
```

@fterpstra Dit is volgens mij niet conform de URI strategie van het register?

**Comment by nicojanbakker** [comment]
Frank zit naast me. Het is volgens hem inderdaad in zekere zin
problematisch. Alleen modellen die ook echt onder een cluster vallen moeten
onder een cluster worden gezet. De overige modellen moeten niet onder het
cluster overig maar moeten op de hoofdpagina zichtbaar zijn.

Dus voor modellen die geclusterd kunnen worden:

http://register.geostandaarden.nl/cluster/m
<http://register.geostandaarden.nl/overig/imkl>odel

Voor niet te clusteren modellen:

http://register.geostandaarden.nl/m
<http://register.geostandaarden.nl/overig/imkl>odel


Op 16 december 2015 14:22 schreef Simeon Nedkov <notifications@github.com>:

**Comment by nicojanbakker** [comment]
Haha, nee niet heel erg ingewikkeld inderdaad.



Op dit moment wordt eerst een overview van clusters aangemaakt mbv
cluster.json en vervolgens wordt een overzicht van de repos in het cluster
gemaakt mbv repos.json. Dit laatst gebeurd alleen voor het cluster waarin
het model geplaatst moet worden.



Wat misschien wel het makkelijkste is: repos.json gebruiken om de clusters
en de niet geclusterde modellen te beschrijven (dus alles wat op de
hoofdpagina moet).  En vervolgens, indien het model inderdaad onderdeel is
van cluster, een ander .json gebruiken om een overview voor het betreffende
cluster te creeeren.



Is een kwestie van een if statement toevoegen en structuur/vulling van de
json bestanden veranderen.

Op 16 december 2015 14:37 schreef Nico-Jan Bakker <nicojanbakker@gmail.com>:
