### ISSUE TITLE
Toevoegen -dev repositories

### ISSUE THREAD

**Issue by ghost** [Geonovum/technisch-register#36]
Hallo Simeon,

Ik heb van Frank de opdracht gekregen een -dev versie van de volgende repositories te maken:
-imro, -pcp, -imropt en -stri. Maar ik wil deze -dev repositories toevoegen zonder dat er iets op register.geostandaarden of op register.geostandaarden/staging gepubliceerd wordt. Zou jij hiervoor de volgende lege repositories kunnen aanmaken op https://github.com/Geonovum:
imro-dev
pcp-dev
imropt-dev
stri-dev
Dan kan ik ze clonen en ze gevuld weer terug committen. Tenminste ik denk dat dit de makkelijkste manier is. Aangezien ik zelf geen repositories kan aanmaken op https://github.com/Geonovum maar jij wel. 

Alvast bedankt!

**Comment by ndkv** [comment]
Check. Ik heb je overal collaborator met admin rechten gemaakt. Je kan als het goed is alles editen. 

Kun je controleren of alles werkt door bijv. de READMEs aan te vullen?

**Comment by ghost** [comment]
Getest en het werkt. Dankjewel.

Op 22 december 2015 15:34 schreef Simeon Nedkov notifications@github.com:

> Check. Ik heb je overal collaborator met admin rechten gemaakt. Je kan als
> het goed is alles editen.
> 
> Kun je controleren of alles werkt door bijv. de READMEs aan te vullen?
>
