### ISSUE TITLE
Lokaal runnen op Windows

### ISSUE THREAD

**Issue by ghost** [Geonovum/technisch-register#37]
Ik ben vandaag begonnen met het uitbreiden van de code zodat deze automatisch zipfiles aanmaakt. Opzich niet spannend  en is waarschijnlijk zo gebeurd. Maar helaas loop ik weer tegen het probleem aan dat lokaal runnen nog niet goed werkt. Het lijkt me goed om dit eerst op te lossen en zo nodig zo snel mogelijk het readme file aan te passen.

Allereerst moest ik weer zelf wat mappen toevoegen. Dit hadden we vorige keer al besproken en komt als het goed is nog in de README. Ik zal de README meteen even updaten. (zie issue 1 en issue 2 in de bijlage)

Daarnaast werkt lokaal runnen met build.py (zoals staat aangegeven in de README) nog niet zoals het hoort. Ik word er zo een twee drie niet wijs uit wat dit kan veroorzaken en hoe ik dit kan oplossen. Heb jij een idee? Zie bijlage onderin voor de Tracebacks.  

Ook lokaal runnen met run.py blijkt zoals te verwachten bij mij niet te werken. De code runt wel, creeert html pagina's maar vult deze niet met artefacten. Zie hiervoor ook de bijlage

@Simeon: Zou je even naar de tracebacks in de bijlage kunnen kijken? En mij vertellen waar jij denkt dat het fout gaat?

Alvast bedankt.

[ProblemenLokaalRunnen.docx](https://github.com/Geonovum/technisch-register/files/89010/ProblemenLokaalRunnen.docx)

**Comment by ndkv** [comment]
Zie 'setup' branch en issue #30.

Ben morgen de hele dag op pad. Ik kijk er vrijdag naar. 

On 13 January 2016 16:09:06 CET, notifications@github.com wrote:

> Ik ben vandaag begonnen met het uitbreiden van de code zodat deze
> automatisch zipfiles aanmaakt. Opzich niet spannend  en is
> waarschijnlijk zo gebeurd. Maar helaas loop ik weer tegen het probleem
> aan dat lokaal runnen nog niet goed werkt. Het lijkt me goed om dit
> eerst op te lossen en zo nodig zo snel mogelijk het readme file aan te
> passen.
> 
> Allereerst moest ik weer zelf wat mappen toevoegen. Dit hadden we
> vorige keer al besproken en komt als het goed is nog in de README. Ik
> zal de README meteen even updaten. (zie issue 1 en issue 2 in de
> bijlage)
> 
> Daarnaast werkt lokaal runnen met build.py (zoals staat aangegeven in
> de README) nog niet zoals het hoort. Ik word er zo een twee drie niet
> wijs uit wat dit kan veroorzaken en hoe ik dit kan oplossen. Heb jij
> een idee? Zie bijlage onderin voor de Tracebacks.  
> 
> Ook lokaal runnen met run.py blijkt zoals te verwachten bij mij niet te
> werken. De code runt wel, creeert html pagina's maar vult deze niet met
> artefacten. Zie hiervoor ook de bijlage
> 
> @Simeon: Zou je even naar de tracebacks in de bijlage kunnen kijken? En
> mij vertellen waar jij denkt dat het fout gaat?
> 
> Alvast bedankt.
> 
> [ProblemenLokaalRunnen.docx](https://github.com/Geonovum/technisch-register/files/89010/ProblemenLokaalRunnen.docx)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Geonovum/technisch-register/issues/37

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicojanbakker** [comment]
Oke prima! alvast bedankt!

Aanvullende informatie:

1- Wanneer ik build.py vanuit gitBash run verdwijnt de traceback zodra ik 'shell = True' gebruik voor 'Popen (.........)'. Maar dan nog steeds gaat het niet goed: run.py wordt niet automatisch aangeroepen. build.py runt dus wel maar trapt run.py niet af. 

2- Build.py runnen in IDLE geeft (onafhankelijk van gebruik shell = True) de volgende Traceback:

Traceback (most recent call last):
  File "C:/Users/NBakker/Desktop/testbuild", line 20, in <module>
    Popen(['/usr/bin/python', 'run.py'], stdin=stdin, stdout=fp, stderr=STDOUT, shell = True)
  File "C:\Program Files (x86)\Python2.7.8\lib\subprocess.py", line 702, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "C:\Program Files (x86)\Python2.7.8\lib\subprocess.py", line 832, in _get_handles
    p2cread = msvcrt.get_osfhandle(stdin.fileno())
UnsupportedOperation: fileno

Ik lees verschillende oplossingen op forums maar wordt er nog niet heel veel wijs uit. Heb jij een idee hoe dit het beste is op te lossen?

**Comment by ndkv** [comment]
Oplossing voor issues 1 en 2 is het aanmaken van een `initialize.py` script die de nodige mappen aanmaakt en alle repos binnenhaalt. Wederom, zie `setup` branch.

Issue 3 is vrij duidelijk

```
WindowsError: [Error 2] The system cannot find the file specified. 
```

Iets op lijn 20 van `build.py` kan een bestand niet vinden. Daar wordt naar twee bestanden gerefereerd: de Python executable in `usr/bin/python` en `run.py`. Fout wordt door het eerste bestand veroorzaakt: het pad `/usr/bin/python` bestaat niet op Windows.

Oplossing: `python_path` in `settings.py` opnemen en deze per configuratie (server, OS X, Windows) aanpassen.

Ik weet niet hoe je `run.py` probeert te runnen maar het is in principe te verwachten dat ie niet werkt omdat ie input van `stdin` verwacht, zie lijn 18.

Verder kun je `build.py` niet vanuit IDLE uitvoeren omdat je dan geen toegang hebt tot de UNIX commando's zoals `cp` die hier en daar gebruikt worden. Ik weet ook niet hoe IDLE `git` aanroept (en of ie dat uberhaupt doet). Daarom moet je het in git Bash runnen (of https://github.com/babun/babun).

**Comment by ghost** [comment]
Bedankt voor je reactie. Helaas blijkt het antwoord op issue 3 nog niet zo
eenvoudig als je dacht. Het klopt inderdaad dat het pad naar python
verkeerd stond om het werkend te krijgen op windows. Maar ook na aanpassen
van het pad gaat het nog steeds niet goed. Het pad wordt gebruikt om bij
'subprocess.py' te komen. Eenmaal daar aangekomen gaat het mis (zie
onderstaande traceback). Hij kan _errread, errwrite en *_startupinfo *niet
vinden.

Als mogelijke oplossing op internet wordt het veranderen van de 'compspec'
path variable genoemd, zodat deze niet meer naar C://Windows/system32/*cmd.exe
*verwijst. Hier durf ik mij niet aan te wagen want dat gaat waarschijnlijk
ook mijn andere windows processen slopen.

Andere optie die mogelijk veel problemen oplost, en veel eenvoudiger is, is
dat ik een Virtual machine met daarop Ubuntu installer en van daaruit de
code ga runnen. Waarschijnlijk ook beter om dit voor windows gebruikers in
de handleiding aan te bevelen. Beter dan ze allemaal instellingen te laten
veranderen. Lijkt me bovendien ook makkelijker bij het developen. Wat is
jou mening hierover?

_File "build.py", line 21, in <module>_
-    Popen(['python_path', 'run.py'], stdin=stdin, stdout=fp,
  stderr=STDOUT)*
-  File "C:\Program Files (x86)\Python2.7.8\lib\subprocess.py", line 710,
  in **init***
-    errread, errwrite)*
-  File "C:\Program Files (x86)\Python2.7.8\lib\subprocess.py", line 958,
  in _execute_child*
-    startupinfo)*
  _WindowsError: [Error 2] The system cannot find the file specified_

Op 15 januari 2016 14:22 schreef Simeon Nedkov notifications@github.com:

**Comment by ndkv** [comment]
Je roept `Popen` aan als

```
Popen(['python_path', 'run.py'], stdin=stdin, stdout=fp, stderr=STDOUT)
```

Moet dat niet 

```
Popen([python_path, 'run.py'], stdin=stdin, stdout=fp, stderr=STDOUT)
```

zijn i.e. `python_path` zonder aanhalingstekens? Ik neem aan dat je naar een variabele refereert?

Een elegantere oplossing is om de Python pad executable via `sys.executable` te specificeren, zie http://stackoverflow.com/questions/912830/using-subprocess-to-run-python-script-on-windows#912847 Ik pas dit zo aan in `master`.

Het devven zal zeker eenvoudiger zijn op Linux. We hoeven op z'n minst niet meer te gissen of een bug door Windows of iets anders veroorzaakt wordt. Tegelijkertijd is het installeren van een VM/Linux en het onderhouden van een tweede dev omgeving een gedoetje. Het zou mooi zijn als we het aan de praat krijgen in Windows; ik ben destijds op Win + Git Bash begonnen en het werkte prima.

Welke shell gebruik je trouwens? De scripts hebben een Unix shell nodig en zullen niet in de Windows command prompt werken (o.a. door de symbolic links i.e. `ln -s` is een ongeldige commando in `cmd.exe`).

**Comment by ghost** [comment]
Bedankt voor je reactie.

Vandaag opnieuw geprobeerd de code te runnen op windows. Via GitBash
uiteraard. Ik heb netjes de REAME handleiding gevolgd en meteen ook even
het gedeelte onder het kopje installing letterlijk uitgevoerd. Handig dat
dit er nu allemaal ook in staat. En bovendien is het goed te volgen. Dus
dit ging uiteindelijk goed, maar ik liep nog wel tegen wat issues aan.

Allereerst lukte het 'installeren' in Git Bash alleen vanuit administrator
mode. Misschien logisch maar lijkt me toch goed om dit aan de handleiding
toe te voegen. Daarnaast begon gitBash te klagen over backslashes die
meekomen in path verwijzingen vanuit windows. Om dit op te lossen heb ik
wat aanpassingen aan de code gedaan. Hiervoor staat nu een pull request
uit.

Wat betreft het daadwerkelijk runnen van de code: Na weghalen
vervangen 'python_path'
door python_path verdwijnt inderdaad de volgende Error: *WindowsError:
[Error 2] The system cannot find the file specified. *Maar hier komt meteen
een nieuwe voor in de plaats: *WindowsError: [Error 5] Access is denied. *Dit
terwijl ik Git-Bash gewoon in administrator mode run. Zelfs wanneer ik alle
applicaties volle rechten geeft op de betreffende mappen blijft deze error
bestaan. Heb jij toevallig een idee waar dit door veroorzaakt wordt?

Groeten, Nico-Jan

Op 20 januari 2016 20:17 schreef Simeon Nedkov notifications@github.com:

**Comment by ndkv** [comment]
Ok, kleine stapjes voorwaarts. 

Ik heb in principe altijd de stack trace nodig om te zien wat er mis is. Het kan zijn dat bijv. backend.py crasht omdat een andere module een foutmelding genereert. Met enkel Access denied kan ik weinig, ik weet bijv. niet welke map je probeert te benaderen. 

En voel je a.u.b. vrij om de README uit te breiden. Ik kom de Windows-specifieke zaken niet tegen.

**Comment by ghost** [comment]
Bedankt voor de snelle reactie. Kleine stapjes voorwaarts inderdaad. Er zit
gelukkig nog progressie in.
Hieronder de betreffende traceback.

Top, ik ga de README meteen uitbreiden.

Starting sync script...
Traceback (most recent call last):
  File "build.py", line 23, in <module>
    Popen([python_path, path.join(root_path, 'run.py').replace('\', '/')],
stdin=stdin, stdout=fp, stderr=STDOUT)
  File "C:\Program Files (x86)\Python2.7.8\lib\subprocess.py", line 710, in
**init**
    errread, errwrite)
  File "C:\Program Files (x86)\Python2.7.8\lib\subprocess.py", line 958, in
_execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied

Op 4 februari 2016 22:04 schreef Simeon Nedkov notifications@github.com:

**Comment by ndkv** [comment]
Heb in het weekend een Windows VM op Amazon geregeld om de code te debuggen. Ik kwam een hoop issues met de paden tegen. Hoewel Git Bash een Unix-achtige omgeving is, draait Python in 'Windows' mode waardoor modules backwardslashes retourneren ipv forwardslashes.
- Probleem: `os.path.join()` gebruikt backwardslashes ipv forwardslashes
  Oplossing: module `posixpath` gebruiken ipv `os.path`.
- `OSFS.getsyspath()` retourneert paden met backslashes 
  Oplossing: gebruik `fs.path.ospath` of `.replace('\\', '/')` om backslashes te vervangen met forwardslashes
- Probleem: Git Bash en OSFS gebruiken verschillende notities voor root en absolute paden. OSFS vertaalt `/` naar `/c`. Git Bash doet dat niet. Dit zorgt voor problemen bij o.a. de calls `cp` en `git`. Als je paden uit `settings.py` gebruikt klaagt Git Bash dat `/Users/` niet betstaat omdat het `/c/Users` moet zijn.
  Oplossing: detecteer wanneer code op Windows draait en injecteer `/c` voor de absolute paden in `settings.py`
- Probleem: `git clone` werkt niet op paden met spaties bijv. `My Documents`. Dit ben ik nog aan het onderzoeken maar het lijkt erop dat Git Bash moeite heeft met uitvoeren van `git clone` vanuit Python als 't pad spaties heeft.

Enzovoort... en ik heb niet eens `build.py` geprobeerd te runnen. Kortom, de boel werkt inderdaad niet op Windows.

@fterpstra Bovenstaand is op te lossen, de vraag is: willen we het werkend hebben op Windows? Investeren in Windows is natuurlijk mogelijk maar wellicht niet zo zinnig als het op OS X / Linux werkt en het opzetten van VirtualBox + Ubuntu VM vrij eenvoudig is.

**Comment by ndkv** [comment]
@ghost We hebben besloten om ondersteuning voor Windows voorlopig te laten voor wat het is. 

Ik breid de README uit met HowTo install Linux VM in VirtualBox.
