### ISSUE TITLE
informatiemodellen clusteren

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/technisch-register#4]
Informatiemodellen in de secundaire ingang kunnen optioneel geclusterd worden in sets van gerelateerde informatie modellen. Bij voorbeeld ruimtelijke ordening modellen of BRT modellen
rationale:
Voor de buitenwereld zijn deze sets van modellen bekend als één geheel  bekend. Indviduele modellen meteen op de hoofdpagina zetten leidt tot verwarring en een gebrek aan overzicht
Fit criterium:
De mogelijkheid om te configureren dat op de hoofdpagina van het technisch  register een ingang van een groep van informatiemodellen verschijnt

**Comment by ghost** [comment]
Hallo Simeon,

Vandaag ben ik begonnen met het clusteren van de informatiemodellen. Dit gaat opzich wel goed, alleen loop ik bij het lokaal proef runnen op mijn pc tegen de volgende traceback aan: 

bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

Vervolgens geprobeerd lxml opnieuw te installeren. Dit lukte ook niet en geeft de volgende foutmelding: 

ERROR: 'xslt-config' is not recognized as an internal or external command,
    operable program or batch file.
  *\* make sure the development packages of libxml2 and libxslt are installed \*                  *

Nu wil ik dus eigenlijk libxml2 en libxslt installeren. Nu vroeg ik me af of jij nog tips hebt waar ik libxml2 en libxslt het beste kan downloaden en hoe ik zet het makkelijkst kan installeren. Pogingen om dit te doen faalden tot nu toe. Dus ik vroeg me af hoe jij dit gedaan hebt. En of het uberhaupt nodig is.

Mvg,
Nico-Jan

**Comment by ndkv** [comment]
lxml is in principe niet nodig. Het schijnt wel sneller te zijn dan de ingebouwde parser. Aangezien het om hele kleine documenten gaat kunnen we prima uit te voeten met `html.parser` ipv `lxml`. Zie laatste commit.

**Comment by ghost** [comment]
De informatie modellen zijn geclusterd. Ik heb net een pull request gedaan. Er is nu ook een extra json file bij gekomen waarin de clusters beschreven staan. De beschrijvingen in deze file (cluster.json) moeten nog even worden aangepast. Net zoals de linkjes van de modellen naar de cluster. Zodat alles straks onder het juiste cluster staat en deze ook goed beschreven is.
