### ISSUE TITLE
imkl2015 gedeelte van register werkt niet

### ISSUE THREAD

**Issue by ndkv** [Geonovum/technisch-register#41]
Probleem: link op hoofdpagina linkt naar `imkl` ipv `imkl2015`.

**Comment by ndkv** [comment]
Ik heb het handmatig gefixt (naar juiste map in `index.html` linken) en ga nu onderzoeken waarom build script naar `imkl` ipv `imkl2015` linkt terwijl laatste in `repos.json` vermeld is.

**Comment by ghost** [comment]
Zou het kunnen dat de URL in repos.json verkeerd staat?

Op 25 januari 2016 11:39 schreef Simeon Nedkov notifications@github.com:

**Comment by ndkv** [comment]
Opgelost: link op hoofdpagina wordt opgebouwd uit `id` waarde in `cluster.json`*. IMKL heette hier `imkl` ipv `imkl2015`.

Ik was nog in de veronderstelling dat niet geclusterde informatiemodellen hun gegevens uit `repos.json` halen ipv `cluster.json`.

**Comment by ndkv** [comment]
URL in `repos.json` had ik al gefixt inderdaad.

**Comment by ndkv** [comment]
Ok, fix staat op server. Getest door laatste IMKL2015 release nog eens naar server via GitHub web interface.
