### ISSUE TITLE
Travis CI intergratie

### ISSUE THREAD

**Issue by ndkv** [Geonovum/technisch-register#45]
Ik heb gisteren de repository aan [Travis CI](https://travis-ci.org/) gelinkt. Na elke commit pullt Travis de repo en voert de tests uit. De status van de laatste run/commit vindt je in de README onder het build schildje. Deze kan de waardes passing/failing aannemen. Klik erop om een rapport te zien. 

Handig, maar wat veel handiger is dat Travis automatisch alle pull requests test. Je kan (eenmaal alle tests geschreven zijn) of een bijdrage de code breekt. Op deze manier kunnen we bijv. (nu al) syntax fouten in aangeleverde `repos.json` en `cluster.json` vinden omdat ze de tests zullen breken.

**Comment by ndkv** [comment]
De Travis checks in actie: https://github.com/Geonovum/technisch-register/pull/46

**Comment by ghost** [comment]
Nice! :) Ik zag het net pas. De volgende keer zal ik er ook echt gebruik van maken.

**Comment by ndkv** [comment]
Je hebt er al gebruik van gemaakt. :) Zie rood kruisje achter je pull request in het overzicht. Dat duidt op een mislukte run. Op de issue pagina pagina zie je welke tests mislukt zijn, zie https://github.com/Geonovum/technisch-register/pull/47 Als je doorklikt naar Travis zie je de foutmelding: https://travis-ci.org/Geonovum/technisch-register/builds/106991736 Het lijkt erop dat er een haakje op lijn 68 van backend.py ontbreekt.
