### ISSUE TITLE
Inhoud staging niet helemaal gelijk aan live

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/technisch-register#9]
Ik mis hier imgeo-simple.xsd http://register.geostandaarden.nl/staging/gmlapplicatieschema/BGT-IMGeo/2.1.1/

Hier staat een citygml2.0 folder, op live niet: http://register.geostandaarden.nl/staging/xmlschema/BGT-IMGeo/1.2/

Hier mist een 1.0.1 folder die wel op live staat: http://register.geostandaarden.nl/staging/wsdl/BGT-IMGeo/

**Comment by fterpstra** [comment]
de cityGML2.0 folder staat juist wel op live maar bevat alleen een lege subfolder. Heb hem overgezet naar github maar betwijfel of hij iets toevoegd

**Comment by ndkv** [comment]
Hmmm... git(hub?) doet volgens mij niets met lege mappen. Waarschijnlijk komt ie nog steeds niet door. 

Is het niet beter om map weg te halen als deze leeg is?

**Comment by fterpstra** [comment]
overlegd met marcel, de citygmlfolder hoort niet leeg te zijn, dit aangepast in github.
